services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=profitflowdb'
      - 'POSTGRES_PASSWORD=pass'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pfnet

  profitflow:
    build:
      context: ProfitFlow
      dockerfile: ProfitFlow/Dockerfile
    container_name: class-service
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/profitflowdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    networks:
      - pfnet
    volumes:
      - ~/.m2:/root/.m2

networks:
  pfnet:
    driver: bridge