services:
  postgres:
    image: postgres:16
    container_name: pfdatabase
    environment:
      POSTGRES_DB: profitflowdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pfnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pfnet
    depends_on:
      - postgres

  profitflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profitflow
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/profitflowdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    ports:
      - "8080:8080"
    networks:
      - pfnet
    volumes:
      - ~/.m2:/root/.m2

networks:
  pfnet:
    driver: bridge

volumes:
  pgdata: